// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableTopics(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAvailableTopics'](arg1, arg2, arg3);
}

export function GetCallClassifiers(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCallClassifiers'](arg1, arg2, arg3);
}

export function GetChatClassifiers(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetChatClassifiers'](arg1, arg2, arg3);
}

export function GetDailyData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDailyData'](arg1, arg2, arg3);
}

export function GetDatabaseStats() {
  return window['go']['main']['App']['GetDatabaseStats']();
}

export function GetHourlyData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetHourlyData'](arg1, arg2, arg3, arg4);
}

export function GetMonthlyData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMonthlyData'](arg1, arg2, arg3);
}

export function GetOverallClassifiers(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetOverallClassifiers'](arg1, arg2, arg3);
}

export function GetQueueStats(arg1, arg2) {
  return window['go']['main']['App']['GetQueueStats'](arg1, arg2);
}

export function GetSubtopicsDaily(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetSubtopicsDaily'](arg1, arg2, arg3, arg4);
}

export function GetTopics(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTopics'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function TestMongoDBConnection() {
  return window['go']['main']['App']['TestMongoDBConnection']();
}

export function TestMongoDBConnectionDetailed() {
  return window['go']['main']['App']['TestMongoDBConnectionDetailed']();
}

export function TestMySQLConnection() {
  return window['go']['main']['App']['TestMySQLConnection']();
}
