// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableTopics(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetCallClassifiers(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetChatClassifiers(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetDailyData(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetDatabaseStats():Promise<Record<string, any>>;

export function GetHourlyData(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function GetMonthlyData(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetOverallClassifiers(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetQueueStats(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetSubtopicsDaily(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function GetTopics(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function TestMongoDBConnection():Promise<string>;

export function TestMongoDBConnectionDetailed():Promise<Record<string, any>>;

export function TestMySQLConnection():Promise<string>;
